### ISSUE TITLE
[Feature] max-statements-per-line

### ISSUE THREAD

**Issue by LucasFalkowsky** [typedigital/eslint-config-typedigital#113]
**Is there something missing in our code style? Please describe.**

We should discuss, weather a maximum of 2 statements is benefitting our code.

**Describe how the feature should be implemented to fit your needs.**

defining multiple changeable variables in one line, fore example inside a function, could benefit the readability of our code, since all necessary definitions are done in one line, as done with params. Also the file length is not unnecessarily lengthened.

**Additional context**

I would love to define variables like this:
`let name; let age; let address;`
The eslint rule for this fix would be max-statements-per-line.

**Comment by timidak** [comment]
Is this really a use case? 
You could simply do this: 
```ts
let x, y, z;
// or
const t = 1, r = 2;
```
But enabling more than two statements per line makes the code harder to read imho. This could lead to things like

```ts
const res = fn(a); console.log(a); const secRes = fn(b); console.log(secRes);
```
In my opinion, readability suffers from this. Can you think of any other use case where it could be beneficial?

**Comment by LucasFalkowsky** [comment]
The problem with the solution you presented is, that this is in conflict with our declaration of the eslint `one-var` rule. We simply can not use one declaration for multiple variables.

**Comment by timidak** [comment]
Oh you're right, but allowing multiple statements per line could make our code less readable. So in my opinion this can't be the answer. 
Also, the `one-var` rule helps us with only atomic changes. 
For example if I want to change the variable type of bar to let, I have to change multiple lines, if we declare it like this:
```diff
function foo() {
-    const bar, 
-          baz;
+   let bar;
+   const baz;
   var baz;
    let qux,
        norf;
}
```

It would be better if we explicitly set the variable type for each variable so we only have to change the one.
```diff
function foo() {
-    const bar; 
+   let bar;
    const baz;
    var baz;
    let qux;
    let  norf;
}
```
In my opinion the code is more readable with a maximum of two statements per line and also the `one-var` rule helps us keep the changes clean.

**Comment by JoeTypeDigital** [comment]
I agree with @timidak here.
I would like to add that this rule also disincentivizes mixing declarations which is very bad codestyle imho.
`let a = 1; let b; let c;`
And it gets way worse if you aren't declaring variables but as @timidak commented try to do anything else;

I do not see a use case for this either.

**Comment by timidak** [comment]
I added a `wontfix` tag, if we could come back to this later or close the issue. Feel free @JoeTypeDigital @LucasFalkowsky
