### ISSUE TITLE
[Bug] Enum already declared in the upper scope warning

### ISSUE THREAD

**Issue by JenniferFalkenstein** [typedigital/eslint-config-typedigital#116]
**Describe the bug**

When declaring Enums we usually get a warning `Enum is already declared in the upper-scope` and referencing to the same line where it was just declared

**Context**

- Rule: no-shadow
- config: base
and
- Rule: @typescript/no-shadow
- config: typescript

**To Reproduce**
1. Open a new typescript file
2. Declare, e.g. `enum exampleEnum { ONE, TWO }`
3. See warning message

**Expected behavior**

The warning should only appear, when it really has been declared somewhere else in this file, not in the same line

**Screenshots**

![Bildschirmfoto 2023-03-14 um 09 39 45](https://user-images.githubusercontent.com/80680536/224943859-a6ab0e51-17e2-4b98-9fc2-dec093190ace.png)

**Additional context**
I found a solution here https://stackoverflow.com/questions/63961803/eslint-says-all-enums-in-typescript-app-are-already-declared-in-the-upper-scope

**Comment by timidak** [comment]
Thank you @JenniferFalkenstein for reporting 🥇. This behavior could be avoided by disabling the rule `no-shadow` in the typescript config, I guess!

**Comment by JoeTypeDigital** [comment]
Well, this sound as if we were to disable this rull completely which cannot be the correct course of action. This rule should prevent duplicate naming in nested functions and I think that is correct to keep.
According to this bug report (https://github.com/typescript-eslint/typescript-eslint/issues/2483) the solution is to additionally disable eslint-no-shadow as that seems to cause the issue.
I haven't tested this though.
