### ISSUE TITLE
[Bug] no-magic-numbers clashes with styled-components

### ISSUE THREAD

**Issue by timidak** [typedigital/eslint-config-typedigital#28]
**Describe the bug**

If you are using styled-components and need numbers to calculate widths or just set them the `no-magic-numbers` rule clashes with it. 

**Context**

_It is best to provice which config (e.g. base or react) and rule is affected._
- Rule: _no-magic-numbers_
- config: _base_

**Expected behavior**

We could either turn that rule off or think about a styled-components eslint-config which disables the clashing rules.

**Comment by timidak** [comment]
I would add a special config for styled-components (`styled-components.js`) where we disable this rule and maybe some others that clash in the future.
Or we turn the rule off completely. I'm not sure. What do you think @JoeTypeDigital?

**Comment by JoeTypeDigital** [comment]
I think no-magic-numbers is in general a good rule outside of styled-components. So I'd rather see a solution involving a special rule set for that particular case than getting rid of it entirely.

**Comment by timidak** [comment]
I guess we will use styled-components in most of our projects, so we could either turn the rule off, as it will warn us all the time when writing styled-component code otherwise. 
Or we have a new config with one rule turned off, which has to be imported in a certain order otherwise it would warn anyway. 
The order would be sth. like:
- base
- react
- styled-components

Do you think the initial invest is ok for only one rule in the first place, @JoeTypeDigital.
