### ISSUE TITLE
[Bug] Spacing is not really applied consistent

### ISSUE THREAD

**Issue by timidak** [typedigital/eslint-config-typedigital#35]
**Describe the bug**

When you create and object `const result = { x: 5, y: []}` space is applied before the key but not after the last value. Maybe because it's an array? Maybe not.

**Context**

_It is best to provice which config (e.g. base or react) and rule is affected._
- Rule: ?
- config: base

**Expected behavior**

It should apply consistent spacing.

**Screenshots**

![Anmerkung](https://user-images.githubusercontent.com/18395108/90898945-7b9b6500-e3c7-11ea-8781-4eb4f8d7694c.jpg)

**Comment by JoeTypeDigital** [comment]
Could you elaborate what the issue is? As far as I can see the rule enforces a space before the key and not after for each key value pair. How would a "fixed" version of your object look like?

**Comment by timidak** [comment]
It would be more consistent if we apply space consistently. So between the array and the closing curly brace there should be a space, I guess. 

| before   |      after      | 
|:----------:|:-------------:|
| `const result = { x: 5, y: []}` |  `const result = { x: 5, y: [] }` | 

Is that clear now, @JoeTypeDigital?
