### ISSUE TITLE
[Feature] Consistent file naming

### ISSUE THREAD

**Issue by timidak** [typedigital/eslint-config-typedigital#68]
**Is there something missing in our code style? Please describe.**

We should enforce consistent file naming in our projects. 

**Describe how the feature should be implemented to fit your needs.**

In most cases we use `kebab-case` for files but file name casing is often missed in reviews. In my opinion we should enforce it with a rule.

**Additional context**

I also found the plugin [eslint-plugin-unicorn](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/filename-case.md) which could help us enforcing file name casing.

Adding this rule would break older codebases, if the use other file name casings.

**Comment by bob606** [comment]
Adressed in #75
