### ISSUE TITLE
[Feature] Arrow function with too many parameters. Why not?

### ISSUE THREAD

**Issue by timidak** [typedigital/eslint-config-typedigital#97]
**Is there something missing in our code style? Please describe.**

I do not exactly know why we limited the parameters of our arrow functions. We use them heavily and sometimes you need more params. 
Imho this rule also leads to anti patterns like summarizing multiple parameters in a parameters object. 

**Describe how the feature should be implemented to fit your needs.**

We should either have a clear opinion about this or disable the rule.

**Additional context**

![Bildschirmfoto 2022-07-28 um 13 18 28](https://user-images.githubusercontent.com/18395108/182386220-826331de-68f4-4501-b191-98e20ffaf68f.png)

**Comment by LucasFalkowsky** [comment]
I am on your side on this one. I never understood the rule and it's not always possible to use less parameters for a function.
